=== DavidLDM/LND2017/practica16/ejercicios3y4/ejercicio3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!-- simples -->  

<xs:element name="fecha" type="xs:date"/>

<xs:element name="nombre_entidad">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>   
  
  
<xs:element name="nombre">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="id">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="apellidos">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="telefono">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="tipo_calle">
  <xs:simpleType>
    <xs:restriction base="xs:string">
    <xs:enumeration value="calle"/>
    <xs:enumeration value="avenida"/>
    <xs:enumeration value="plaza"/> 
      <xs:pattern value="[a-zA-Z]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="nombre_calle">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="numero">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="piso_letra">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]+[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="cp">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="localidad">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="provincia">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="num_prestamo">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="concepto">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<xs:element name="cantidad">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element> 

<!-- complex -->

<xs:element name="documento">
<xs:complexType>
<xs:sequence>
<xs:element ref="nombre_entidad"/>
<xs:element ref="fecha"/>
<xs:element ref="datos"/>
<xs:element ref="prestamos"/>
</xs:sequence>
</xs:complexType>
</xs:element>


<xs:element name="direccion">
<xs:complexType>
<xs:sequence>
<xs:element ref="tipo_calle"/>
<xs:element ref="nombre_calle"/>
<xs:element ref="numero"/>
<xs:element ref="piso_letra"/>
<xs:element ref="cp"/>
<xs:element ref="localidad"/>
<xs:element ref="provincia"/>
</xs:sequence>
</xs:complexType>
</xs:element>


<xs:element name="datos">
<xs:complexType>
<xs:sequence>
<xs:element ref="id"/>
<xs:element ref="nombre"/>
<xs:element ref="apellidos"/>
<xs:element ref="telefono"/>
<xs:element ref="direccion"/>
</xs:sequence>
</xs:complexType>
</xs:element>


<xs:element name="prestamos">
<xs:complexType>
<xs:sequence>
<xs:element ref="num_prestamo"/>
<xs:element ref="concepto"/>
<xs:element ref="cantidad"/>
</xs:sequence>
</xs:complexType>
</xs:element>


</xs:schema>

=== DavidLDM/LND2017/practica16/ejercicios3y4/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<documento xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "ejercicio3.xsd">
<nombre_entidad>Bankia</nombre_entidad>

<fecha>2011-02-02</fecha>

<datos>
<id>647837</id>
<nombre>David</nombre>
<apellidos>MartinezMontero</apellidos>
<telefono>928527348</telefono>
<direccion>
<tipo_calle>calle</tipo_calle>
<nombre_calle>LosPoceros</nombre_calle>
<numero>27</numero>
<piso_letra>x0</piso_letra>
<cp>35600</cp>
<localidad>PuertodelRosario</localidad>
<provincia>LasPalmas</provincia>
</direccion>
</datos>

<prestamos>
<num_prestamo>33545</num_prestamo>
<concepto>Hipoteca</concepto>
<cantidad>2000</cantidad>
</prestamos>

</documento>
